//
// Created by Francesco Taccetti on 11/07/2022.
//

#ifndef TACCETTIELABORATO_DEFINITIONS_H
#define TACCETTIELABORATO_DEFINITIONS_H

//SCREEN
#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 675

//PLAYER
#define PLAYER_DIMENSIONS 60.0
#define PLAYER_POSX 200

//JUMP
#define GRAVITY 0.09
#define JUMP_FORCE (-28)
#define MAX_YVELOCITY 15

//PROJECTILES
#define PROJECTILE_SPEED 2.5
#define PROJECTILE_COOLDOWN 250

//ENEMIES
#define ENEMY_DIMENSIONS 60
#define ENEMY_COOLDOWN 700
#define ENEMY_SPEED 1


#endif //TACCETTIELABORATO_DEFINITIONS_H
