//
// Created by Francesco Taccetti on 11/07/2022.
//

#ifndef TACCETTIELABORATO_DEFINITIONS_H
#define TACCETTIELABORATO_DEFINITIONS_H

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 675

#define PLAYER_DIMENSIONS 60
#define PLAYER_POSX 200

#define GRAVITY 0.09
#define JUMP_FORCE -27
#define MAX_YVELOCITY 70


#endif //TACCETTIELABORATO_DEFINITIONS_H
